// <auto-generated />
namespace FreeSpace.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addscanExpetionsandtweakvarchars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addscanExpetionsandtweakvarchars));
        
        string IMigrationMetadata.Id
        {
            get { return "201811120513145_add scanExpetions and tweak varchars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
